

version: '3.9'
services:
  api:
    image: gcr.io/techworld-438822/techworld-backend:latest
    container_name: lds-api
    environment:
      - LDS_BUCKET=${LDS_BUCKET}
      - LDS_RESOURCE_PATH=${LDS_RESOURCE_PATH}
      - LDS_REST_PORT=${LDS_REST_PORT}
      - LDS_MYSQL_INSTANCE=${LDS_MYSQL_INSTANCE}
      - LDS_MYSQL_DATABASE=${LDS_MYSQL_DATABASE}
      - LDS_MYSQL_USERNAME=${LDS_MYSQL_USERNAME}
      - LDS_MYSQL_PASSWORD=${LDS_MYSQL_PASSWORD}
      - DATA_INIT_BUCKET_NAME=${DATA_INIT_BUCKET_NAME}
      - DATA_INIT_FILE_NAME=${DATA_INIT_FILE_NAME}
    ports:
      - ${LDS_REST_PORT}:${LDS_REST_PORT}
    networks:
      - lds
    logging:
      driver: gcplogs

  web:
    image: gcr.io/techworld-438822/techworld-frontend:${FRONTEND_VERSION_TAG}
    container_name: lds-web
    environment:
      - LDS_REST_URL=${LDS_REST_URL}
    ports:
      - '80:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - lds
    logging:
      driver: gcplogs

networks:
  lds:
    driver: bridge
