name: Backend Tests , Cloud Build and terraform deploy

on:
  push:
    branches:
      - main
    paths:
      - 'api/pom.xml'
      - 'api/src/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'api/pom.xml'
      - 'api/src/**'
      - '.github/workflows/backend.yml'
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  GCP_SA_KEY: ${{secrets.GCP_SA_KEY }}


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ["17"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'api/pom.xml'

      - name: Install dependencies
        run: mvn -B install -DskipTests
        working-directory: api

      - name: Run tests
        run: mvn -B test
        working-directory: api

      - name: 'Authenticating to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Build docker image with Cloud Build'
        run: |
          cd api
          gcloud builds submit --config cloudbuild.yaml


  packer-build:
    needs: test  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Authenticating to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Authenticate Docker with Google Cloud Registry
      - name: Authenticate Docker to Google Container Registry
        run: gcloud auth configure-docker

      # Trigger Cloud Build to run the Packer script
      - name: Run Cloud Build for Packer
        run: |
          cd cloudbuild-packer-image
          gcloud builds submit --config cloudbuild_packer_vm_img.yaml


  terraform-deploy:
    needs: packer-build 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Authenticating to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Authenticate Docker with Google Cloud Registry
      - name: Authenticate Docker to Google Container Registry
        run: gcloud auth configure-docker

      
      - name: deploy with terraform
        run: |
          cd terraform-deployment
          terraform destroy -auto-approve -var "project_id=${{ secrets.GCP_PROJECT_ID }}"
       # terraform init && terraform destroy --auto-approve -var "project_id=${{ secrets.GCP_PROJECT_ID }}"
          
